theme = "darcula_transparent"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.smart-tab]
# https://github.com/helix-editor/helix/issues/7804
enable = false
