# LSP installation
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "markdown"
soft-wrap = { enable = true }

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.rust-analyzer.config.check]
command = "clippy"
