# LSP installation
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations

[[language]]
name = "go"
auto-format = true
language-servers = ["gopls", "golangci-lint2-langserver"]
formatter = { command = "goimports" }

[[language]]
name = "log"
soft-wrap = { enable = true }

[[language]]
name = "markdown"
soft-wrap = { enable = true }

[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "swift"
formatter = { command = "swift", args = ["format" ] }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "typespec"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "xml"
file-types = [
  "svg",
  "xml",
  "xsd",
  "xsl",
  "xslt",
]

[language-server.golangci-lint2-langserver]
command = "golangci-lint-langserver"

[language-server.golangci-lint2-langserver.config]
command = [
  "golangci-lint",
  "run",
  "--output.json.path",
  "stdout",
  "--show-stats=false",
  "--issues-exit-code=1",
]

[language-server.rust-analyzer.config]
check.command = "clippy"
checkOnSave.enable = true

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json" = "eng/**/*.{yml,yaml}"
