# LSP installation
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations

use-grammars = { only = ["typespec"] }

[[grammar]]
name = "typespec"
source = { git = "https://github.com/happenslol/tree-sitter-typespec", rev = "af7a97eea5d4c62473b29655a238d4f4e055798b" }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "log"
soft-wrap = { enable = true }

[[language]]
name = "markdown"
soft-wrap = { enable = true }

[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "typespec"
language-id = "typespec"
scope = "source.typespec"
injection-regex = "(tsp|typespec)"
file-types = ["tsp"]
roots = ["tspconfig.yaml"]
auto-format = true
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "  " }
language-servers = ["typespec"]

[language-server.rust-analyzer.config]
check.command = "clippy"
checkOnSave.enable = true

[language-server.typespec]
command = "tsp-server"
args = ["--stdio"]
